name: auth
description: Reusable firebase auth widgets and providers, part of FFFW
version: 0.0.1
publish_to: none

environment:
  # sdk: ">=2.17.1 <3.3.3"
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  # firebase_core: ^2.3.0
  firebase_core: ^2.25.4
  # cloud_firestore: ^4.0.1
  cloud_firestore: ^4.15.4
  # firebase_auth: 4.6.3
  firebase_auth: ^4.17.4
  # firebase_auth_web: 5.5.3
  firebase_auth_web: ^5.9.4
  # firebase_auth_platform_interface: 6.15.3
  # flutter_secure_storage: ^9.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^1.1.6
  gap: ^2.0.1
  flutter_web_auth_2: ^2.1.4
  webview_flutter: ^4.2.1
  http: ^0.13.5
  firebase_admin: ^0.2.0
  shelf_router: ^1.1.2
  firebase_dart: ^1.0.3
  url_launcher: ^6.1.14

  providers:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: providers

dependency_overrides:
  providers:
    path: "../providers"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
