name: auth
description: Reusable firebase auth widgets and providers, part of FFFW
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.1 <3.3.3"
  flutter: ">=1.17.0"

dependencies:
  firebase_core: ^2.3.0
  cloud_firestore: ^4.0.1
  firebase_auth: ^4.6.0
  firebase_auth_web: 5.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^1.1.6
  gap: ^2.0.1
  providers:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: providers



# dependency_overrides:
#   providers:
#     path: ../providers


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/google_logo.svg
    - assets/github_logo.svg
      
