name: providers
description: Reusable firestore riverpod providers
version: 0.0.1

environment:
  # sdk: ">=2.17.1 <3.3.3"
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_auth_web: ^5.13.4
  firebase_auth_platform_interface: ^7.4.9
  cloud_firestore: ^5.5.0
  flutter_riverpod: ^2.3.6
  jiffy: ^5.0.0
  # auth:
  #   git:
  #     url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
  #     path: auth

# For testing locally
dependency_overrides:
  auth:
    path: "../auth"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
