name: widgets
description: Widgets for simplicity of UI with Firestore
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.3.3"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  firebase_core: ^2.3.0
  firebase_auth: 4.1.5
  cloud_firestore: ^4.0.1
  jiffy: ^5.0.0
  flutter_riverpod: ^1.0.4
  providers:
    git: 
      url: https://github.com/kovarny/flutter_firebase_framework.git
      path: providers
  common:
    git: 
      url: https://github.com/kovarny/flutter_firebase_framework.git
      path: common


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


