name: widgets
description: Widgets for simplicity of UI with Firestore
version: 0.0.1
publish_to: "none"

environment:
  # sdk: ">=2.17.1 <3.3.3"
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase_core: ^2.3.0
  # firebase_auth: 4.6.3
  # firebase_auth_platform_interface: 6.15.3
  # firebase_core: ^2.3.0
  firebase_core: ^2.25.4
  # cloud_firestore: ^4.0.1
  cloud_firestore: ^4.15.4
  # firebase_auth: 4.6.3
  firebase_auth: ^4.17.4
  # firebase_auth_web: 5.5.3
  firebase_auth_web: ^5.9.4
  # firebase_auth_platform_interface: 6.15.3
  # flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.0
  jiffy: ^5.0.0
  providers:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: providers
  auth:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: auth
  url_launcher: ^6.1.10
  code_editor: ^1.3.2
  code_text_field: ^1.1.0
  google_fonts: ^4.0.3
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

dependency_overrides:
  providers:
    path: ../providers
  auth:
    path: ../auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
