name: widgets
description: Widgets for simplicity of UI with Firestore
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.1 <3.3.3"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  firebase_core: ^2.3.0
  firebase_auth: 4.6.3
  firebase_auth_platform_interface: 6.15.3
  flutter_riverpod: ^2.3.6
  cloud_firestore: ^4.0.1
  jiffy: ^5.0.0
  providers:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      ref: bugfix/prevent-the-blink-of-the-light-theme-on-hard-refresh-if-user-saves-dark-theme
      path: providers
  common:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      ref: bugfix/prevent-the-blink-of-the-light-theme-on-hard-refresh-if-user-saves-dark-theme
      path: common
  auth:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      ref: bugfix/prevent-the-blink-of-the-light-theme-on-hard-refresh-if-user-saves-dark-theme
      path: auth
  theme:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      ref: bugfix/prevent-the-blink-of-the-light-theme-on-hard-refresh-if-user-saves-dark-theme
      path: theme
  url_launcher: ^6.1.10
  code_editor: ^1.3.2
  code_text_field: ^1.1.0
  google_fonts: ^4.0.3
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

dependency_overrides:
  common:
    path: ../common
  providers:
    path: ../providers
  auth:
    path: ../auth
  theme:
    path: ../theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
