name: theme
description: FFFW Themes
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.3.3"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
