name: theme
description: FFFW Themes
version: 0.0.1

environment:
  sdk: ">=2.17.1 <3.3.3"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  cloud_firestore: ^4.0.1
  firebase_auth: 4.6.3
  firebase_auth_web: 5.5.3
  flutter_secure_storage: ^9.0.0
  firebase_auth_platform_interface: 6.15.3
  auth:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      ref: bugfix/prevent-the-blink-of-the-light-theme-on-hard-refresh-if-user-saves-dark-theme
      path: auth
  providers:
    git:
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      ref: bugfix/prevent-the-blink-of-the-light-theme-on-hard-refresh-if-user-saves-dark-theme
      path: providers

dependency_overrides:
  auth:
    path: ../auth
  providers:
    path: ../providers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
