name: common
description: Common constants and types
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.3.3"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.0
  firebase_core: ^2.3.0
  firebase_auth: 4.1.5
  cloud_firestore: ^4.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
